# -*- coding: utf-8 -*-
"""titanic-survival.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FmpYC1etaWwtVNRrPYuiBKL_hUAcIdEn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn. linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

url = 'https://raw.githubusercontent.com/kapilpoonia05/Codsoft-tasks/main/Titanic%20Task/Titanic-Dataset.csv'
df = pd.read_csv(url)

df.head()

df.shape

df.info()

df.isnull().sum()

df = df.drop(columns='Cabin', axis=1)

df.describe()

df.info()

df.isnull().sum()

df['Age'].fillna(df['Age'].mean(),inplace=True)

df.head()

df.info()

df.isnull().sum()

df.describe()

df['Survived'].value_counts()

sns.set()

sns.countplot(x='Survived', data=df)

df[ 'Sex' ].value_counts()

sns.countplot(x='Sex', data=df)

sns.countplot(x= 'Sex', hue='Survived', data=df)

df[ 'Pclass' ].value_counts()

sns.countplot(x='Pclass', data=df)

sns.countplot(x= 'Pclass', hue='Survived', data=df)

# converting categorical Columns
df.replace({'Sex': {'male':0, 'female': 1},'Embarked': {'S' :0, 'C':1, 'Q' :2}}, inplace=True)

df.head()

X = df.drop(columns = ['PassengerId', 'Name', 'Ticket', 'Survived'],axis=1)
Y = df['Survived']

X

Y

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

model = LogisticRegression()

# training the Logistic Regression model with training data
model.fit(X_train, Y_train)

#accuracy on training data
X_train_prediction =model.predict(X_train)

X_train_prediction

training_data_accuracy =accuracy_score(Y_train, X_train_prediction)

training_data_accuracy

#accuracy on lest data
X_test_prediction = model.predict (X_test)

X_test_prediction

test_data_accuracy =accuracy_score(Y_test, X_test_prediction)
print(test_data_accuracy)

