# -*- coding: utf-8 -*-
"""irisflower.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192AMfyD6V4B2b7zysrcc6xwU57z5k7X-
"""

import numpy as np
import pandas as pd
import os

url='https://raw.githubusercontent.com/kapilpoonia05/Codsoft-tasks/main/Iris%20flower%20Classification/IRIS.csv'

# Read the Iris.csv file into a pandas DataFrame
df = pd.read_csv(url)

df.head()

df.head(10)

df.shape

df.info()

df.isnull().sum()

df.describe()

import matplotlib.pyplot as plt

plt.hist(df['sepal_length'])

plt.hist(df['sepal_width'])

df.hist(figsize=(15,10))

import seaborn as sns
from sklearn.model_selection import train_test_split

df['species'].value_counts()

# scatter plot
colors = ['green','red','blue']
species = ['Iris-setosa','Iris-versicolor','Iris-virginica']

for i in range(3):
    x=df[df['species']==species[i]]
    plt.scatter(x['sepal_length'],x['sepal_width'], c=colors[i], label=species[i])
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.legend()

for i in range(3):
    x=df[df['species']==species[i]]
    plt.scatter(x['sepal_length'],x['petal_length'], c=colors[i], label=species[i])
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.legend()

for i in range(3):
    x=df[df['species']==species[i]]
    plt.scatter(x['sepal_width'],x['petal_width'], c=colors[i], label=species[i])
plt.xlabel("Sepal Width")
plt.ylabel("Petal Width")
plt.legend()

for i in range(3):
    x=df[df['species']==species[i]]
    plt.scatter(x['petal_length'],x['petal_width'], c=colors[i], label=species[i])
plt.xlabel("Petal Length")
plt.ylabel("Petal Width")
plt.legend()

#correaltion Matrix
numeric_columns = df.select_dtypes(include=["number"]).columns
df_numeric = df[numeric_columns]
df_numeric.corr()

import seaborn as sns

#Heatmap
cor=df_numeric.corr()
sns.heatmap(cor,annot=True)

df['species'].value_counts()

#REplacing object values with some integer values
species = ['Iris-setosa','Iris-versicolor','Iris-virginica']
for i in range (0,3):
  df['species'].replace({species[i]:i},inplace=True)

df.head()

#Splitting the dataset
X = df.drop(columns='species')
Y=df['species']

X

Y

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

print(X.shape,X_test.shape,X_train.shape);

X_test

X_train

Y_test

Y_train

#Logistic Regression
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X_train,Y_train)

accuracy = model.score(X_test, Y_test)*100
print("Accuracy:", accuracy)

#KNN - K-Nearest Neighbour
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()

model.fit(X_train,Y_train)

accuracy = model.score(X_test, Y_test)*100
print("Accuracy:", accuracy)

#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

model.fit(X_train,Y_train)

accuracy = model.score(X_test, Y_test)*100
print("Accuracy:", accuracy)